### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by mduguil** [mduguil/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create data model telling direction car is facing
- [x] create keydown event listener
- [x] match corresponding keydown to direction
- [x] use css to rotate car
